language: php

# Run on container environment (needed for trais caching feature)
sudo: false

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

env:
  - SYMFONY_VERSION="~3.0"
  - SYMFONY_VERSION="~4.0"

jobs:
  include:
    - php: 7.1
      env: DEPENDENCIES='low' SYMFONY_VERSION="~3.0"
    - php: 7.1
      env: DEPENDENCIES='low' SYMFONY_VERSION="~4.0"

# Cache composer files for faster test times
cache:
  directories:
    - $HOME/.composer/cache

before_install:
  # Remove xdebug module as it is not required but slows down composer and phpunit
  - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then phpenv config-rm xdebug.ini; fi;
  # Attempt to use Github oAuth token, if available, to avoid their public ratelimit
  - if [ -n "$GH_ACCESS_TOKEN" ]; then git config --global github.accesstoken $GH_ACCESS_TOKEN; fi;
  - if [ -n "$GH_ACCESS_TOKEN" ]; then composer config github-oauth.github.com $GH_ACCESS_TOKEN; fi;
  # Composer only updated in TravisCI containers when they build their images every month or so
  - travis_retry composer self-update

install:
  - travis_retry composer require symfony/symfony:${SYMFONY_VERSION}
  - if [ -z "$DEPENDENCIES" ]; then travis_retry composer install --no-interaction --prefer-dist; fi;
  - if [ "$DEPENDENCIES" == "low" ]; then travis_retry composer update --no-interaction  --prefer-dist --prefer-lowest; fi;

script:
  - vendor/bin/phpunit