language: php

# Run on container environment (needed for trais caching feature)
sudo: false

matrix:
  fast_finish: true
  include:
      - php: 7.1
      - php: 7.1
        env: DEPENDENCIES='low'
      - php: 7.2
      - php: 7.3
      - php: 7.4
      - php: hhvm=3.24
  allow_failures:
      - php: hhvm=3.24

env:
  - SYMFONY_VERSION="~3.0"
  - SYMFONY_VERSION="~4.0"

# Cache composer files for faster test times
cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_install:
  # Remove xdebug module as it is not required but slows down composer and phpunit
  - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then phpenv config-rm xdebug.ini; fi;
  # Attempt to use Github oAuth token, if available, to avoid their public ratelimit
  - if [ -n "$GH_ACCESS_TOKEN" ]; then git config --global github.accesstoken $GH_ACCESS_TOKEN; fi;
  - if [ -n "$GH_ACCESS_TOKEN" ]; then composer config github-oauth.github.com $GH_ACCESS_TOKEN; fi;
  # Composer only updated in TravisCI containers when they build their images every month or so
  - composer self-update
  - composer require symfony/symfony:${SYMFONY_VERSION}

install:
  - if [ -z "$DEPENDENCIES" ]; then composer install --no-interaction --prefer-dist; fi;
  - if [ "$DEPENDENCIES" == "low" ]; then composer update --no-interaction  --prefer-dist --prefer-lowest; fi;

script:
  - vendor/bin/phpunit